version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"        # expose Ollama API
    volumes:
      - ollama_data:/root/.ollama   # persist models
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
